local M = {
  INIT_SEX = 0, -- 0为男性，1为女性
  INIT_HEAD = 2002,
  INIT_GOLD = 0,
  INIT_FOOD = 10000,
  INIT_WOOD = 10000,
  INIT_STONE = 0,
  INIT_ORE = 0,
  INIT_GEM = 200,
  INIT_BUILD_FREE_TIME = 300,  -- 免费建造时间
  INIT_AC = 5,
  INIT_MAX_AC = 5,
  INIT_WEATHER_DAYS = 2,
  INIT_UQUEST_COUNT = 10,

  SEX_MALE = 0,
  SEX_FEMALE = 1,

  --AC_RECOVERY = 1,
  --AC_RECOVERY_TIME = 60
  AC_REC_SECONDS_PER_POINT = 60 * 30, --每恢复一点体力需要多少秒
  MAX_ONLINE_REWARDS = 24,
  HIGH_GAMBLE_TIMES = 30,

  CHECK_IN_DAYS = 33,

  UP_BUILDING_EVENT = 30,
  ATTACK_MONSTER_EVENT = 31,
  RESEARCH_EVENT = 32,
  TRAIN_EVENT = 33,
  CURE_EVENT = 34,
  COLLECT_RES_EVENT = 35,

  CITY_FIRE_DURATION = 1800,
  CITY_LOSE_LIFE = 50,

  CITY_FIRE_PER = 6,
  CITY_FIRE_LIFE = 10,

  OPEN_GOLD_LEVEL_LIMIT = 6,
  OPEN_STONE_LEVEL_LIMIT = 11,
  OPEN_ORE_LEVEL_LIMIT = 16,

  DAILY_EXPLORE_CAVE_TIMES = 3, --每日探索洞穴次数

  SWITCH_HERO_POS_CD = 6 * 3600,

  PLUNSER_EFFECT_ID = 8049,
  MARCH_SPEED_EFFECT_ID = 8013,
  UNLOCK_ARMY_EFFECT_ID = 8554,

  FREE_REPAIRE_CITY_LIFE = 120,

  ADD_INCOME_EFFECTS = {
    food = 8501,
    wood = 8502,
    stone = 8503,
    ore = 8504,
    all = 8506,
  },

  NEW_PLAYER_CHEST_DURATION = 86400 * 3,

  DETAIL_CHEST_EXPIRE = 2 * 3600,
}

UserConst = M

return  M